<?php

    function dna_menu() {
        $items['dna_create'] = array(
            'title' => 'DNA helix combination',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('dna_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['dna_success'] = array(
            'title' => 'Results',
            'page callback' => 'dna_display',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );

        return $items;
    }

    function dna_form() {
        $form['dna_input'] = array(
            '#title' => 'DNA Input',
            '#type' => 'textfield',
            '#description' => t('Please input the beginning of a DNA helix combination. The letters have to be a combination of A, T, C, and G.'),
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Get Combination',
        );

        return $form;
    }

    function dna_form_submit($form, &$form_state) {
        $input = $form_state['values']['dna_input'];
        $result = dna_combination($input);
        $_SESSION['result'] = $result;
        $form_state['redirect'] = 'dna_success';
    }

    function dna_combination($input) {
        $exploded_input = str_split(strtoupper($input));

        $results = array();
        for ($i = 0; $i < count($exploded_input); $i++) {
            if ($exploded_input[$i] === "A") {
                array_push($results, "T");
            } else if ($exploded_input[$i] === "T") {
                array_push($results, "A");
            } else if ($exploded_input[$i] === "C") {
                array_push($results, "G");
            } else if ($exploded_input[$i] === "G") {
                array_push($results, "C");
            }
        }

        return implode("", $results);
    }


    function dna_display() {
        $result = $_SESSION['result'];
        return $result;
    }
